"""changed to sqlalchemy recommendation model structure

Revision ID: 06238cfc2d83
Revises: 2bf23169484d
Create Date: 2024-04-26 10:53:59.207628

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '06238cfc2d83'
down_revision = '2bf23169484d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'brand_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'current_price',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=False)
    op.alter_column('products', 'discount_percent',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('products', 'images',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=False)
    op.alter_column('products', 'product_code',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('products', 'selling_fast',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('products', 'selling_fast',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('products', 'product_code',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'images',
               existing_type=postgresql.ARRAY(sa.VARCHAR()),
               nullable=True)
    op.alter_column('products', 'url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'currency',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'discount_percent',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('products', 'current_price',
               existing_type=sa.NUMERIC(precision=8, scale=2),
               nullable=True)
    op.alter_column('products', 'brand_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###
